
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author MrNam
 */
public class DoiMK extends javax.swing.JFrame {
    public static String stk;
    /**
     * Creates new form DoiMK
     */
    public DoiMK() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAcpect = new javax.swing.JButton();
        btnReturn = new javax.swing.JButton();
        lblOldPass = new javax.swing.JLabel();
        lblPass = new javax.swing.JLabel();
        lblConfirm = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        pwOldPass = new javax.swing.JPasswordField();
        pwNewPass = new javax.swing.JPasswordField();
        pwConfirm = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnAcpect.setText("Đồng Ý");
        btnAcpect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcpectActionPerformed(evt);
            }
        });

        btnReturn.setText("Quay Lại");
        btnReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturnActionPerformed(evt);
            }
        });

        lblOldPass.setText("Nhập mật khẩu cũ:");

        lblPass.setText("Nhập mật khẩu mới:");

        lblConfirm.setText("Nhập lại mật khẩu mới:");

        jLabel1.setText("Xin Chào "+stk);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(btnAcpect, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(102, 102, 102)
                        .addComponent(btnReturn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(257, 257, 257)
                        .addComponent(jLabel1)))
                .addContainerGap(162, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblOldPass)
                    .addComponent(lblPass)
                    .addComponent(lblConfirm))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pwOldPass)
                    .addComponent(pwNewPass)
                    .addComponent(pwConfirm))
                .addGap(98, 98, 98))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblOldPass)
                            .addComponent(pwOldPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblPass)
                            .addComponent(pwNewPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(58, 58, 58))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblConfirm)
                        .addComponent(pwConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAcpect)
                    .addComponent(btnReturn))
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAcpectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcpectActionPerformed
        try {
            // TODO add your handling code here:
            //JOptionPane.showMessageDialog(null, getTenDangNhap());
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql:///qltk","root","");
            String sqlcheck= "Select * from taikhoan where sothe=? and matkhau=? ";
            PreparedStatement pst=con.prepareStatement (sqlcheck);
            pst.setString(1, stk);
            pst.setString(2, pwOldPass.getText());
            ResultSet rs= pst.executeQuery();
            if(rs.next()){
                //JOptionPane.showMessageDialog(null, pwNewPass.getText()+"\n"+pwConfirm.getText());
                if(pwNewPass.getText().equals(pwConfirm.getText()))
                {
                    String sqlupdate= "update taikhoan set matkhau=? where sothe=?";
                    PreparedStatement pst1=con.prepareStatement (sqlupdate);
                    pst1.setString(1, pwConfirm.getText());
                    pst1.setString(2, stk);
                    pst1.executeUpdate();
                    JOptionPane.showMessageDialog(null, "Đã đổi mật khẩu thành công");
                    reset();
                }
                else{
                    JOptionPane.showMessageDialog(null, "Nhập lại mật khẩu mới chưa đúng");
                    reset();
                }
            }
            else{
                JOptionPane.showMessageDialog(null, "Mời bạn kiểm tra lại mật khẩu cũ");
                reset();
            }
            con.close();
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(DoiMK.class.getName()).log(Level.SEVERE, null, ex);
        }
        
            
    }//GEN-LAST:event_btnAcpectActionPerformed

    private void btnReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnActionPerformed
        // TODO add your handling code here:
        new GiaoDien().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnReturnActionPerformed
    public static void sotaikhoan(String args[]){
        stk=args[0];
    }
    private void reset(){
        pwOldPass.setText("");
        pwNewPass.setText("");
        pwConfirm.setText("");
        pwOldPass.requestFocus();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DoiMK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DoiMK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DoiMK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DoiMK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DoiMK().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAcpect;
    private javax.swing.JButton btnReturn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblConfirm;
    private javax.swing.JLabel lblOldPass;
    private javax.swing.JLabel lblPass;
    private javax.swing.JPasswordField pwConfirm;
    private javax.swing.JPasswordField pwNewPass;
    private javax.swing.JPasswordField pwOldPass;
    // End of variables declaration//GEN-END:variables
}
