
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author MrNam
 */
public class TaoTaiKhoan extends javax.swing.JFrame {

    /**
     * Creates new form TaoTaiKhoan
     */
    public TaoTaiKhoan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSoThe = new javax.swing.JLabel();
        lblMatKhau = new javax.swing.JLabel();
        lblConfirm = new javax.swing.JLabel();
        lblHoTen = new javax.swing.JLabel();
        txtSoThe = new javax.swing.JTextField();
        lblSoTienDaNap = new javax.swing.JLabel();
        pwMatKhau = new javax.swing.JPasswordField();
        pwConfirm = new javax.swing.JPasswordField();
        txtHoTen = new javax.swing.JTextField();
        txtSoTienNap = new javax.swing.JTextField();
        btnDongY = new javax.swing.JButton();
        btnQuayLai = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblSoThe.setText("Số thẻ:");

        lblMatKhau.setText("Mật khẩu:");

        lblConfirm.setText("Nhập lại mật khẩu:");

        lblHoTen.setText("Họ tên:");

        lblSoTienDaNap.setText("Số tiền đã nạp:");

        btnDongY.setText("Đồng Ý");
        btnDongY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDongYActionPerformed(evt);
            }
        });

        btnQuayLai.setText("Quay Lại");
        btnQuayLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuayLaiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblConfirm)
                            .addComponent(lblMatKhau, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblSoThe, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblHoTen, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblSoTienDaNap, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pwMatKhau)
                            .addComponent(pwConfirm)
                            .addComponent(txtHoTen)
                            .addComponent(txtSoTienNap, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                            .addComponent(txtSoThe)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(btnDongY, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(btnQuayLai)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSoThe)
                    .addComponent(txtSoThe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMatKhau)
                    .addComponent(pwMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblConfirm)
                    .addComponent(pwConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHoTen)
                    .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSoTienDaNap)
                    .addComponent(txtSoTienNap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnQuayLai)
                    .addComponent(btnDongY))
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDongYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDongYActionPerformed
        try {
                    // TODO add your handling code here:
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql:///qltk","root","");
            String sqlcheck= "Select * from taikhoan";
            PreparedStatement pst1=con.prepareStatement (sqlcheck);
            ResultSet rs= pst1.executeQuery();
            if(rs.next()){
                if(pwMatKhau.getText().equals(pwConfirm.getText()) && !rs.getString("sothe").equals(txtSoThe.getText())){
                    if(Integer.parseInt(txtSoTienNap.getText())>=50000){
                    String sql= "insert into taikhoan (sothe,matkhau,sodu,hoten) value (?,?,?,?)";
                    PreparedStatement pst=con.prepareStatement (sql);
                    pst.setString(1, txtSoThe.getText());
                    pst.setString(2, pwMatKhau.getText());
                    pst.setInt(3, Integer.parseInt(txtSoTienNap.getText()));
                    pst.setString(4, txtHoTen.getText());
                    pst.executeUpdate();
                    con.close();
                    JOptionPane.showMessageDialog(null, "Tạo tài khoản thành công");
                    txtHoTen.setText("");
                    txtSoThe.setText("");
                    txtSoTienNap.setText("");
                    pwConfirm.setText("");
                    pwMatKhau.setText("");
                    txtSoThe.requestFocus();
                    }
                }
                else
                    JOptionPane.showMessageDialog(null, "Tài khoản không hợp lệ");
                    txtHoTen.setText("");
                    txtSoThe.setText("");
                    txtSoTienNap.setText("");
                    pwConfirm.setText("");
                    pwMatKhau.setText("");
                    txtSoThe.requestFocus();
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(TaoTaiKhoan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnDongYActionPerformed

    private void btnQuayLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuayLaiActionPerformed
        // TODO add your handling code here:
        new GiaoDien().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnQuayLaiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TaoTaiKhoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TaoTaiKhoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TaoTaiKhoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TaoTaiKhoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TaoTaiKhoan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDongY;
    private javax.swing.JButton btnQuayLai;
    private javax.swing.JLabel lblConfirm;
    private javax.swing.JLabel lblHoTen;
    private javax.swing.JLabel lblMatKhau;
    private javax.swing.JLabel lblSoThe;
    private javax.swing.JLabel lblSoTienDaNap;
    private javax.swing.JPasswordField pwConfirm;
    private javax.swing.JPasswordField pwMatKhau;
    private javax.swing.JTextField txtHoTen;
    private javax.swing.JTextField txtSoThe;
    private javax.swing.JTextField txtSoTienNap;
    // End of variables declaration//GEN-END:variables
}
